.TH "Speed Dreams 2 car spec converter from NFS" "6" "March 2012" "Speed Dreams 2.x" "Games"
.SH NAME
.LP
sd2-nfsperf \- Car Specifications Converter from 'Need for Speed' to Speed Dreams 2
.SH SYNOPSIS
.LP
\fBsd2-nfsperf\fP [-c category.xml] [-i <input carp.txt>] [-o output carp.xml]
.SH DESCRIPTION
This manual describes the Car Specifications Converter application that is shipped with Speed Dreams 2.
.SH OPTIONS
.TP
.B -c \fIcategory.xml\fP
car category description
.TP
.B -i \fIinput carp.txt\fP
input NFS carp.txt
.TP
.B -o \fIoutput carp.xml\fP
converted parameters
.SH LICENSE
sd2-nfsperf is licensed under the GNU General Public License, version 2 or later.
.SH COPYRIGHT
The Speed Dreams Team.
.SH AUTHOR
This manual page was written by Jean-Philippe Meuret <pouillot@users.sourceforge.net>,
based on TORCS 1.2.2 version by Rudy Godoy <rudy@kernel-panik.org>,
for the Debian project ; of course, it may be used by any other.
.SH BUG REPORTS
.br
In case you discover a bug (sure you won't ;-), please report it here:
.br
http://sourceforge.net/p/speed-dreams/tickets/
.br
of course after checking that it is not already filed.
.SH SEE ALSO
Web site: http://www.speed-dreams.org/
.br
Community: http://community.speed-dreams.org/
.br
Sourceforge pages: http://sourceforge.net/projects/speed-dreams/
.br
Wiki: http://sourceforge.net/p/speed-dreams/wiki/Home/
.br
sd2-nfs2ac(6), sd2-accc(6), speed-dreams-2(6), sd2-menuview(6), sd2-trackgen(6)
